Repository HelixNetwork/pendulum, pull requests merged in 2019-11, with the labels that each got.

#224 Refactoring
  .gitignore
  docker/docker-compose-dev.yml
  docker/run-dev.sh
  pom.xml
  src/main/java/net/helix/pendulum/Pendulum.java
  src/main/java/net/helix/pendulum/TransactionValidator.java
  src/main/java/net/helix/pendulum/event/EventContext.java
  src/main/java/net/helix/pendulum/event/EventManager.java
  src/main/java/net/helix/pendulum/event/EventType.java
  src/main/java/net/helix/pendulum/event/Key.java
  src/main/java/net/helix/pendulum/event/PendulumEventListener.java
  src/main/java/net/helix/pendulum/network/DatagramFactory.java
  src/main/java/net/helix/pendulum/network/Node.java
  src/main/java/net/helix/pendulum/network/PacketData.java
  src/main/java/net/helix/pendulum/network/TransactionRequesterWorker.java
  src/main/java/net/helix/pendulum/network/UDPReceiver.java
  src/main/java/net/helix/pendulum/network/impl/DatagramFactoryImpl.java
  src/main/java/net/helix/pendulum/network/impl/RequestQueueImpl.java
  src/main/java/net/helix/pendulum/network/impl/TipRequesterWorkerImpl.java
  src/main/java/net/helix/pendulum/network/impl/TxPacketData.java
  src/main/java/net/helix/pendulum/network/replicator/ReplicatorSourceProcessor.java
  src/main/java/net/helix/pendulum/service/API.java
  src/main/java/net/helix/pendulum/service/ApiArgs.java
  src/main/java/net/helix/pendulum/service/milestone/impl/LatestSolidMilestoneTrackerImpl.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneServiceImpl.java
  src/main/java/net/helix/pendulum/service/milestone/impl/SeenMilestonesRetrieverImpl.java
  src/main/java/net/helix/pendulum/service/spentaddresses/impl/SpentAddressesProviderImpl.java
  src/main/java/net/helix/pendulum/storage/Tangle.java
  src/test/java/net/helix/pendulum/TransactionValidatorTest.java
  src/test/java/net/helix/pendulum/network/NodeTest.java
  src/test/java/net/helix/pendulum/network/TransactionRequesterTest.java
Labels: Refactor

#237 Jenkinsfile & Makefile
  Jenkinsfile
  Makefile
  pom.xml
Labels: devops

#238 give the user a chance to change the spent addresses db path
  docker/docker-compose-dev.yml
  docker/run-dev.sh
  src/main/java/net/helix/pendulum/service/spentaddresses/impl/SpentAddressesProviderImpl.java
Labels: config

#235 Transaction should be confirmed only after balance is updated.
  src/main/java/net/helix/pendulum/controllers/TransactionViewModel.java
  src/main/java/net/helix/pendulum/service/API.java
  src/main/java/net/helix/pendulum/service/ledger/impl/LedgerServiceImpl.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneTrackerImpl.java
Labels: additional-info-needed

#239 log all tangle published messages into a separate file for processing
  src/main/java/net/helix/pendulum/TransactionValidator.java
  src/main/java/net/helix/pendulum/controllers/TransactionViewModel.java
  src/main/java/net/helix/pendulum/storage/Tangle.java
  src/main/resources/logback-save.xml
Labels: devops
