Repository HelixNetwork/pendulum, pull requests merged in 2019-09, with the labels that each got.

#172 Bump undertow.version from 1.4.6.Final to 2.0.26.Final …
  pom.xml
Labels: dependencies

#177 Dev utests
  src/main/java/net/helix/pendulum/service/spentaddresses/impl/SpentAddressesProviderImpl.java
  src/test/java/net/helix/pendulum/TransactionTestUtils.java
  src/test/java/net/helix/pendulum/service/APIIntegrationTest.java
  src/test/java/net/helix/pendulum/service/spentaddresses/impl/SpentAddressesProviderImplTest.java
  src/test/java/net/helix/pendulum/utils/dag/DAGHelperTest.java
Labels: unit-test

#178 urandom tip selection with config param TIPSELECTION_ALPHA = 0
  src/main/java/net/helix/pendulum/service/tipselection/EntryPointSelector.java
  src/main/java/net/helix/pendulum/service/tipselection/RatingCalculator.java
  src/main/java/net/helix/pendulum/service/tipselection/Walker.java
  src/main/java/net/helix/pendulum/service/tipselection/impl/CumulativeWeightCalculator.java
  src/main/java/net/helix/pendulum/service/tipselection/impl/RatingOne.java
  src/main/java/net/helix/pendulum/service/tipselection/impl/TipSelectorImpl.java
  src/main/java/net/helix/pendulum/service/tipselection/impl/WalkerAlpha.java
  src/test/java/net/helix/pendulum/service/tipselection/impl/CumulativeWeightCalculatorTest.java
  src/test/java/net/helix/pendulum/service/tipselection/impl/RatingOneTest.java
  src/test/java/net/helix/pendulum/service/tipselection/impl/WalkerAlphaTest.java
Labels: enhancement

#181 Fix CORS in nginx.conf
  README.md
Labels: devops, network
