Repository HelixNetwork/pendulum, pull requests merged in 2019-12, with the labels that each got.

#241 Lsmt refactor
  src/main/java/net/helix/pendulum/service/milestone/impl/LatestSolidMilestoneTrackerImpl.java
Labels: Refactor, readability

#247 Configuration refactor
  .gitignore
  CHANGELOG.md
  src/main/java/net/helix/pendulum/conf/APIConfig.java
  src/main/java/net/helix/pendulum/conf/BasePendulumConfig.java
  src/main/java/net/helix/pendulum/conf/Config.java
  src/main/java/net/helix/pendulum/conf/ConsensusConfig.java
  src/main/java/net/helix/pendulum/conf/GraphConfig.java
  src/main/java/net/helix/pendulum/conf/MainnetConfig.java
  src/main/java/net/helix/pendulum/conf/MilestoneConfig.java
  src/main/java/net/helix/pendulum/conf/PendulumConfig.java
  src/main/java/net/helix/pendulum/conf/ProtocolConfig.java
  src/main/java/net/helix/pendulum/conf/RoundConfig.java
  src/main/java/net/helix/pendulum/conf/SnapshotConfig.java
  src/main/java/net/helix/pendulum/conf/SpentAddressesConfig.java
  src/main/java/net/helix/pendulum/conf/TestnetConfig.java
  src/main/java/net/helix/pendulum/conf/ValidatorConfig.java
  src/main/java/net/helix/pendulum/conf/ValidatorManagerConfig.java
  src/main/java/net/helix/pendulum/conf/XIConfig.java
  src/main/java/net/helix/pendulum/conf/ZMQConfig.java
  src/main/java/net/helix/pendulum/service/API.java
  src/main/java/net/helix/pendulum/service/Feature.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestonePublisher.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneServiceImpl.java
  src/main/java/net/helix/pendulum/service/snapshot/impl/SnapshotProviderImpl.java
  src/main/java/net/helix/pendulum/service/spentaddresses/impl/SpentAddressesProviderImpl.java
  src/main/java/net/helix/pendulum/service/transactionpruning/async/AsyncTransactionPruner.java
  src/main/java/net/helix/pendulum/service/transactionpruning/async/MilestonePrunerJobQueue.java
  src/main/java/net/helix/pendulum/service/validator/impl/ValidatorServiceImpl.java
  src/main/java/net/helix/pendulum/service/validatormanager/impl/ValidatorManagerServiceImpl.java
  src/main/java/net/helix/pendulum/service/validatormanager/impl/ValidatorPublisher.java
  src/test/java/net/helix/pendulum/conf/ConfigTest.java
  src/test/java/net/helix/pendulum/conf/ZMQConfigTest.java
  src/test/java/net/helix/pendulum/service/spentaddresses/impl/SpentAddressesProviderImplTest.java
Labels: Refactor

#249 remove time check for milestones
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneTrackerImpl.java
Labels: fix

#244 Fix 242
  src/main/java/net/helix/pendulum/service/validatormanager/impl/CandidateTrackerImpl.java
Labels: fix

#250 Merkle check
  src/main/java/net/helix/pendulum/controllers/RoundViewModel.java
  src/main/java/net/helix/pendulum/utils/collections/impl/BoundedLinkedListImpl.java
  src/main/java/net/helix/pendulum/utils/collections/interfaces/BoundedLinkedSet.java
Labels: fix, logging

#263 Export metrics to tangle log
  .gitignore
  Makefile
  src/main/java/net/helix/pendulum/TransactionValidator.java
  src/main/java/net/helix/pendulum/network/Node.java
  src/main/java/net/helix/pendulum/service/API.java
  src/main/java/net/helix/pendulum/service/TipsSolidifier.java
  src/main/java/net/helix/pendulum/service/snapshot/impl/LocalSnapshotManagerImpl.java
  src/main/java/net/helix/pendulum/service/validatormanager/impl/CandidateTrackerImpl.java
  src/test/java/net/helix/pendulum/service/snapshot/impl/LocalSnapshotManagerImplTest.java
Labels: logging

#255 Dev fix db lock
  src/main/java/net/helix/pendulum/Pendulum.java
  src/main/java/net/helix/pendulum/service/spentaddresses/impl/SpentAddressesProviderImpl.java
  src/test/java/net/helix/pendulum/service/APIIntegrationTest.java
  src/test/java/net/helix/pendulum/service/spentaddresses/impl/SpentAddressesProviderImplTest.java
Labels: fix

#258 roundDuration should be read off from config, not defaults
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneTrackerImpl.java
  src/main/java/net/helix/pendulum/service/snapshot/impl/SnapshotServiceImpl.java
Labels: fix

#264 Refactoring
  src/main/java/net/helix/pendulum/BundleValidator.java
  src/main/java/net/helix/pendulum/TransactionValidator.java
  src/main/java/net/helix/pendulum/crypto/Merkle.java
  src/main/java/net/helix/pendulum/network/impl/TipBroadcasterWorkerImpl.java
  src/main/resources/logback-save.xml
Labels: fix
