Repository HelixNetwork/pendulum, pull requests merged in 2019-10, with the labels that each got.

#187 Minor changes for reader comprehension
  src/main/java/net/helix/pendulum/TransactionValidator.java
  src/main/java/net/helix/pendulum/conf/APIConfig.java
  src/main/java/net/helix/pendulum/conf/BasePendulumConfig.java
  src/main/java/net/helix/pendulum/network/Node.java
  src/main/java/net/helix/pendulum/service/API.java
  src/main/java/net/helix/pendulum/service/Graphstream.java
  src/main/java/net/helix/pendulum/service/restserver/resteasy/RestEasy.java
  src/main/resources/logback-save.xml
  src/test/java/net/helix/pendulum/conf/ConfigTest.java
  src/test/java/net/helix/pendulum/service/restserver/RestEasyTest.java
Labels: Refactor, readability

#197 1.0.1
  .gitignore
  CHANGELOG.md
  README.md
  docker/docker-compose-cluster.yml
  docker/ssl/nginx-image/nginx-udp.conf
  docker/ssl/nginx-image/pendulum-cluster.conf
  pom.xml
  src/main/java/net/helix/pendulum/Main.java
  src/main/java/net/helix/pendulum/TransactionValidator.java
  src/main/java/net/helix/pendulum/service/ledger/impl/LedgerServiceImpl.java
  src/main/java/net/helix/pendulum/service/milestone/impl/LatestSolidMilestoneTrackerImpl.java
  src/main/java/net/helix/pendulum/service/snapshot/impl/LocalSnapshotManagerImpl.java
  src/main/java/net/helix/pendulum/service/snapshot/impl/SnapshotImpl.java
  src/main/java/net/helix/pendulum/service/snapshot/impl/SnapshotProviderImpl.java
  src/main/java/net/helix/pendulum/service/snapshot/impl/SnapshotServiceImpl.java
  src/main/java/net/helix/pendulum/service/spentaddresses/impl/SpentAddressesServiceImpl.java
Labels: docs, logging

#198 1.0.2
  .gitignore
  CHANGELOG.md
  README.md
  pom.xml
  src/main/java/net/helix/pendulum/BundleValidator.java
  src/main/java/net/helix/pendulum/Main.java
  src/main/java/net/helix/pendulum/Pendulum.java
  src/main/java/net/helix/pendulum/TransactionValidator.java
  src/main/java/net/helix/pendulum/conf/APIConfig.java
  src/main/java/net/helix/pendulum/conf/BasePendulumConfig.java
  src/main/java/net/helix/pendulum/conf/MilestoneConfig.java
  src/main/java/net/helix/pendulum/conf/PendulumConfig.java
  src/main/java/net/helix/pendulum/conf/SpamConfig.java
  src/main/java/net/helix/pendulum/controllers/RoundViewModel.java
  src/main/java/net/helix/pendulum/controllers/TransactionViewModel.java
  src/main/java/net/helix/pendulum/crypto/Merkle.java
  src/main/java/net/helix/pendulum/model/persistables/Transaction.java
  src/main/java/net/helix/pendulum/service/API.java
  src/main/java/net/helix/pendulum/service/ApiArgs.java
  src/main/java/net/helix/pendulum/service/Spammer.java
  src/main/java/net/helix/pendulum/service/ledger/impl/LedgerServiceImpl.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestonePublisher.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneServiceImpl.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneTrackerImpl.java
  src/main/java/net/helix/pendulum/service/snapshot/impl/SnapshotImpl.java
  src/main/java/net/helix/pendulum/service/snapshot/impl/SnapshotServiceImpl.java
  src/main/java/net/helix/pendulum/service/validator/impl/ValidatorServiceImpl.java
  src/main/java/net/helix/pendulum/service/validatormanager/CandidateSolidifier.java
  src/main/java/net/helix/pendulum/service/validatormanager/CandidateTracker.java
  src/main/java/net/helix/pendulum/service/validatormanager/CandidateValidity.java
  src/main/java/net/helix/pendulum/service/validatormanager/ValidatorManagerException.java
  src/main/java/net/helix/pendulum/service/validatormanager/ValidatorManagerService.java
  src/main/java/net/helix/pendulum/service/validatormanager/impl/CandidateSolidifierImpl.java
  src/main/java/net/helix/pendulum/service/validatormanager/impl/CandidateTrackerImpl.java
  src/main/java/net/helix/pendulum/service/validatormanager/impl/ValidatorManagerServiceImpl.java
  src/main/java/net/helix/pendulum/service/validatormanager/impl/ValidatorPublisher.java
  src/main/java/net/helix/pendulum/storage/rocksdb/RocksDBPersistenceProvider.java
Labels: API, consensus, docs, enhancement, help wanted, logging

#201 Fix MilestoneCandidate processing
  src/main/java/net/helix/pendulum/conf/BasePendulumConfig.java
Labels: API, fix

#202 dev-merge
  .gitignore
  src/main/java/net/helix/pendulum/conf/BasePendulumConfig.java
  src/main/java/net/helix/pendulum/service/snapshot/impl/LocalSnapshotManagerImpl.java
Labels: merge

#205 Fix issues in confirmation
  src/main/java/net/helix/pendulum/controllers/RoundViewModel.java
  src/main/java/net/helix/pendulum/model/persistables/Hashes.java
  src/main/java/net/helix/pendulum/model/persistables/Round.java
  src/main/java/net/helix/pendulum/model/persistables/Validator.java
  src/main/java/net/helix/pendulum/service/API.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneServiceImpl.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneTrackerImpl.java
Labels: API, consensus, debug

#203 Debugging messages, refactor of APITest, and change of API.storeTransactions
  pom.xml
  src/main/java/net/helix/pendulum/network/Node.java
  src/main/java/net/helix/pendulum/service/API.java
  src/main/java/net/helix/pendulum/service/TipsSolidifier.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestonePublisher.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneServiceImpl.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneTrackerImpl.java
  src/main/java/net/helix/pendulum/service/snapshot/impl/LocalSnapshotManagerImpl.java
  src/main/java/net/helix/pendulum/service/snapshot/impl/SnapshotProviderImpl.java
  src/main/java/net/helix/pendulum/utils/PendulumIOUtils.java
  src/main/resources/logback-save.xml
  src/test/java/net/helix/pendulum/service/APITest.java
  src/test/java/net/helix/pendulum/service/tipselection/impl/WalkerAlphaTest.java
Labels: Refactor, logging

#206 1.0.3-pre-release
  CHANGELOG.md
  README.md
  pom.xml
  src/main/java/net/helix/pendulum/Main.java
  src/main/java/net/helix/pendulum/controllers/RoundViewModel.java
  src/main/java/net/helix/pendulum/model/persistables/Hashes.java
  src/main/java/net/helix/pendulum/model/persistables/Round.java
  src/main/java/net/helix/pendulum/model/persistables/Validator.java
  src/main/java/net/helix/pendulum/service/API.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneServiceImpl.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneTrackerImpl.java
Labels: API, consensus

#209 add trace msgs for balance inconsistency checks
  src/main/java/net/helix/pendulum/service/ledger/impl/LedgerServiceImpl.java
Labels: debug, logging

#210 Snapshot tx
  src/main/java/net/helix/pendulum/TransactionValidator.java
  src/main/java/net/helix/pendulum/controllers/RoundViewModel.java
  src/main/java/net/helix/pendulum/utils/PendulumUtils.java
  src/test/java/net/helix/pendulum/utils/PendulumUtilsTest.java
Labels: logging, protocol, unit-test

#213 Inconsistent balance when spamming 0 value in testnet #208
  src/main/java/net/helix/pendulum/model/persistables/Transaction.java
  src/main/java/net/helix/pendulum/service/ledger/impl/LedgerServiceImpl.java
  src/test/java/net/helix/pendulum/service/APITest.java
Labels: fix

#212 1.0.3-patch
  .gitignore
  .travis.yml
  CHANGELOG.md
  pom.xml
  src/main/java/net/helix/pendulum/Main.java
  src/main/java/net/helix/pendulum/conf/BasePendulumConfig.java
  src/main/java/net/helix/pendulum/conf/MilestoneConfig.java
  src/main/java/net/helix/pendulum/conf/TestnetConfig.java
  src/main/java/net/helix/pendulum/service/API.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestonePublisher.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneTrackerImpl.java
  src/main/java/net/helix/pendulum/service/snapshot/impl/LocalSnapshotManagerImpl.java
  src/main/java/net/helix/pendulum/service/snapshot/impl/SnapshotServiceImpl.java
  src/main/java/net/helix/pendulum/service/spentaddresses/impl/SpentAddressesServiceImpl.java
Labels: config, fix

#214 Dev utests
  src/main/java/net/helix/pendulum/controllers/TagViewModel.java
  src/main/java/net/helix/pendulum/model/TagHash.java
  src/test/java/net/helix/pendulum/TangleMockUtils.java
  src/test/java/net/helix/pendulum/controllers/RoundViewModelTest.java
  src/test/java/net/helix/pendulum/controllers/TagViewModelTest.java
  src/test/java/net/helix/pendulum/controllers/TransactionViewModelTest.java
  src/test/java/net/helix/pendulum/service/snapshot/impl/LocalSnapshotManagerImplTest.java
  src/test/java/net/helix/pendulum/service/tipselection/impl/WalkValidatorImplTest.java
Labels: fix, logging, unit-test

#216 Key rotation temporary fix
  src/main/java/net/helix/pendulum/service/validatormanager/impl/CandidateTrackerImpl.java
Labels: fix

#217 1.0.4 pre-release
  CHANGELOG.md
  README.md
  pom.xml
  src/main/java/net/helix/pendulum/Main.java
Labels: fix, unit-test

#218 ZMQ topics for visualisation
  CHANGELOG.md
  README.md
  src/main/java/net/helix/pendulum/network/Node.java
  src/main/java/net/helix/pendulum/service/API.java
  src/main/java/net/helix/pendulum/service/milestone/impl/LatestSolidMilestoneTrackerImpl.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneTrackerImpl.java
Labels: feature

#219 Minor changes to some log.trace calls
  CHANGELOG.md
  src/main/java/net/helix/pendulum/TransactionValidator.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneTrackerImpl.java
  src/main/java/net/helix/pendulum/service/snapshot/impl/SnapshotImpl.java
Labels: logging

#220 Remove obsolete stats package
  README.md
  src/main/java/net/helix/pendulum/Pendulum.java
  src/main/java/net/helix/pendulum/service/stats/TimeWindowedApproveeCounter.java
  src/main/java/net/helix/pendulum/service/stats/TransactionStatsPublisher.java
Labels: Refactor

#221 Fixes & Cleanup
  CHANGELOG.md
  pom.xml
  src/main/java/net/helix/pendulum/Main.java
  src/main/java/net/helix/pendulum/service/API.java
  src/main/java/net/helix/pendulum/service/dto/GetBalancesResponse.java
  src/main/java/net/helix/pendulum/service/ledger/LedgerService.java
  src/main/java/net/helix/pendulum/service/ledger/impl/LedgerServiceImpl.java
  src/main/java/net/helix/pendulum/service/milestone/MilestoneService.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneServiceImpl.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneTrackerImpl.java
  src/main/java/net/helix/pendulum/service/snapshot/SnapshotProvider.java
  src/main/java/net/helix/pendulum/service/snapshot/impl/SnapshotProviderImpl.java
  src/main/java/net/helix/pendulum/service/tipselection/impl/WalkValidatorImpl.java
  src/main/java/net/helix/pendulum/service/transactionpruning/TransactionPruner.java
  src/main/java/net/helix/pendulum/service/transactionpruning/async/AsyncTransactionPruner.java
  src/main/java/net/helix/pendulum/service/transactionpruning/async/MilestonePrunerJobQueue.java
  src/main/java/net/helix/pendulum/service/transactionpruning/jobs/MilestonePrunerJob.java
  src/main/java/net/helix/pendulum/service/validatormanager/impl/CandidateTrackerImpl.java
  src/main/java/net/helix/pendulum/utils/log/ProgressLogger.java
  src/main/java/net/helix/pendulum/utils/log/interval/IntervalLogger.java
Labels: fix, readability

#222 add massive tracings
  src/main/java/net/helix/pendulum/service/milestone/impl/LatestSolidMilestoneTrackerImpl.java
  src/main/java/net/helix/pendulum/service/milestone/impl/MilestoneTrackerImpl.java
Labels: logging
